### ISSUE TITLE
How can I change the configuration of the mod ?, when I try and save it nothing happens and it stays the same.

### ISSUE THREAD

**Issue by alvaroG02** [tristankechlo/ToolLeveling#10]
**Describe the bug**
The changes I make to the mod cannot be saved

**Expected behavior**
I hope I can save the changes that I make to the mod configuration

**Comment by tristankechlo** [comment]
I need some more information to help you.
Which Minecraft/Forge/Mod version are you using?
Have you tried restarting your server/client after saving the configs?

**Comment by HopsandBarley** [comment]
This is happening to me too.  I update the config file, and when i start the game back up, the "toollevelling.json" config file gets overwritten, and it goes back to the default file.   The "item_values.json" file has not gotten reset in my limited testing.
